### ISSUE TITLE
Call to an undefined method json()

### ISSUE THREAD

**Issue by wasifiqbal1990** [JoeDawson/amazon-ecs#12] opened 2017-03-30 08:27 UTC
Hi,

It seems like an amazing library for my use but I am facing the same issue that was reported earlier. 

I tried to check the of status by using "\Amazon::search('Home Alone')->getStatusCode()" and its giving me 400. Can you please check this out for me. 

Thanks in advance. :)

**Comment by joedawson** [comment] 2017-03-30 08:30
Hey @wasifiqbal1990,

Thanks for trying out this package. As you mentioned, this has been raised in a previous issue - #6 

This happens when the search finds no results, I haven't had a chance to fix this yet. I'll try and look at it this weekend. In the meantime, I'll close this issue as it's a duplicate of #6 and if you could leave any further info there that would be appreciated.

**Closed as completed by joedawson** 2017-03-30 08:30 UTC
Labels: duplicate

**Comment by wasifiqbal1990** [comment] 2017-03-30 11:19
Hey, 

Really thanks for your quick response. I did search against the "Home alone" as per your example. And home alone did have results on amazon. So I am not sure what I am doing wrong. Can you please guide me about that ?

Thanks.
